version: '3.8'
services:
  myapp:
    image: medical-clinic
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/medical-clinic-db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
      - proxy
    ports:
      - "8080:8080"
    networks:
      - med-net

  proxy:
    image: medical-clinic-proxy
    environment:
      - FEIGN_CLIENT_medical-clinic-Client_URL=http://myapp:8080
      - SPRING_DATASOURCE_MONGODB_URI=mongodb://mongodb:27017/proxy-db
    ports:
      - "8088:8088"
    networks:
      - med-net

  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=medical-clinic-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - med-net

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: proxy-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - med-net

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local

networks:
  med-net:
    driver: bridge