DELETE FROM appointment
ALTER TABLE appointment ALTER COLUMN id RESTART WITH 1

DELETE FROM doctor
ALTER TABLE doctor ALTER COLUMN id RESTART WITH 1

DELETE FROM patient
ALTER TABLE patient ALTER COLUMN id RESTART WITH 1

